### ISSUE TITLE
stylelint: Unexpected unknown at-rule "@define-mixin"

### ISSUE THREAD

**Issue by etroynov** [alfa-laboratory/arui-presets-lint#35]
Не распознаются миксины:
<img width="665" alt="Screenshot 2020-03-22 at 19 43 56" src="https://user-images.githubusercontent.com/4591518/77255102-215e7280-6c76-11ea-9896-dd2bb67310d1.png">

**Comment by Heymdall** [comment]
Проверил на текущем мастере. 
```css
@define-mixin setFontSize $fontSize {
    font-size: $(fontSize) px;
}

.button {
    @mixin setFontSize 20;
}
```

Работает, не выдает никаких ошибок. Сборка (хоть \то и не относится к этому репозиторию) так же отрабатывает корректно.
